apiVersion: v1
kind: Service
metadata:
    name: react
spec:
    type: LoadBalancer
    selector:
        app: react
        tier: ui
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
    name: chat
spec:
    type: ClusterIP
    selector:
        component: chat
    ports:
        - protocol: TCP
          port: 5000
          targetPort: http
---
apiVersion: v1
kind: Service
metadata: 
    name: jobs
spec:
    type: ClusterIP
    selector:
        component: jobs
    ports:
        - protocol: TCP
          port: 5001
          targetPort: http

---
apiVersion: v1
kind: Service
metadata: 
    name: mapsearch
spec:
    type: ClusterIP
    selector:
        component: mapsearch
    ports:
        - protocol: TCP
          port: 5002
          targetPort: http
---
apiVersion: v1
kind: Service
metadata: 
    name: talent
spec:
    type: ClusterIP
    selector:
        component: talent
    ports:
        - protocol: TCP
          port: 5003
          targetPort: http